apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: cas-charts
  namespace: flux-system
spec:
  type: oci
  url: oci://10.43.12.86:5000/helm      # Zot ClusterIP — always reachable from flux pods
  insecure: true                        # Zot is HTTP only in dev
  interval: 1m
